# Generated by Django 5.0.6 on 2024-05-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Chegirma'),
        ),
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Chegirmadagi narxi'),
        ),
    ]
